[11.0][IMP] Add notes field to calendar
tegin/cb-hr pull request #7
Opened 2019-12-10 16:32 UTC by jarroyomorales

Fast-track

2019-12-11 13:21 UTC, jarroyomorales commented
@etobella Please review, reusing this PR to be able to archive calendars

2019-12-12 13:22 UTC, jarroyomorales commented
@etobella Aprovecho para mejorar unas traducciones del cb_hr_views.
Cuando quieras se puede mergear esto

2019-12-16 11:08 UTC, etobella requested changes

2019-12-16 11:08 UTC, etobella commented on cb_hr_views/views/resource_calendar_views.xml
> +            <xpath expr="//div[@name='button_box']/button[1]" position="attributes">
Change this please...

2019-12-16 11:14 UTC, jarroyomorales commented
@etobella  Comment attended

2019-12-19 17:03 UTC, etobella approved these changes

2019-12-19 17:03 UTC, merged